# Generated by Django 5.0.4 on 2024-04-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='userInfo',
        ),
    ]
